import type { Metadata } from "next";
import { Inter } from "next/font/google";
import TopHeader from "../TopHeader/page";
import Footer from "../Footer/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Buy Me All",
  description: "Generated by create next app",
};

export default function SellerLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <TopHeader />
        {children}
        <Footer />
      </body>
    </html>
  );
}
